name: Code coverage
on:
  pull_request:
    branches: 
      - '*'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest coverage
          python -m pip install .
      - name: Run tests and collect coverage
        run: |
          coverage run -m pytest --cache-clear
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
